version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bash .circleci/install_deps.sh
      - run:
          name: Build code
          command: su --preserve-environment --command "make all" user
      - run:
          name: Test code
          command: su --preserve-environment --command "make test" user
