version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bash .circleci/install_deps.sh
      - run:
          name: Build code
          command: su --preserve-environment --command "echo $PWD; echo $PATH; ls -l; make all" asofi3duser
      - run:
          name: Test code
          command: su --preserve-environment --command "make test" asofi3duser
